---
version: '3'

services:
  fastapi-openai:
    container_name: fastapi-openai
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/fastapi-openai:latest
    restart: always
    networks:
      - db
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/wd:ro
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/uvicorn
    command:
      - app.main:app
      - --host=0.0.0.0
      - --port=8000
      - --reload
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - db
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/postgres/init:/docker-entrypoint-initdb.d
      - ${PWD}/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USET: postgres
      POSTGRES_PASSWORD: postgres
networks:
  db:
    external: false
# volumes:
#   postgres_data:
