---
version: '3'

services:
  rest-api:
    container_name: fastapi-openai
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/fastapi-openai:latest
    # restart: always
    networks:
      - db
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/wd:ro
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/uvicorn
    command:
      - app.main:app
      - --host=0.0.0.0
      - --port=8000
      - --reload
  db:
    container_name: postgres
    image: postgres:latest
    # restart: always
    networks:
      - db
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/db/init:/docker-entrypoint-initdb.d:ro
      - ${PWD}/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
networks:
  db:
    external: false
# volumes:
#   postgres-data:
